CREATE SCHEMA CASO1_BDD;
USE CASO1_BDD;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
	COD_FORNECEDOR INT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(50) NOT NULL,
    TELEFONE_FORNECEDOR VARCHAR(11) NOT NULL,
    ENDERECO_FORNECEDOR VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS(
	COD_FILIAL INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    CAPACIDADE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
	COD_PEDIDO INT PRIMARY KEY,
    DATA_PEDIDO DATETIME NOT NULL,
    PREV_PED DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('ENTREGUE', 'A CAMINHO', 'RECUSADO', 'DEVOLVIDO') NOT NULL,
    CONSTRAINT FK_FORNECEDORES FOREIGN KEY (FORNECEDOR_PEDIDO)
    REFERENCES FORNECEDORES(COD_FORNECEDOR),
    FORNECEDOR_PEDIDO INT NOT NULL
);    

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(	
    DATA_RECEBIMENTO DATETIME NOT NULL,
    CONDICAO_RECEBIMENTO ENUM('BOM ESTADO', 'MAU ESTADO') NOT NULL,
    QNT_PROD_RECEB DECIMAL(8,3) NOT NULL,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY (PEDIDO_RECEBIMENTO) 
	REFERENCES PEDIDOS(COD_PEDIDO),
    PEDIDO_RECEBIMENTO INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
	COD_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    DESCRICAO_PRODUTO TEXT NOT NULL,
    PRECO_UND DECIMAL(8,3) NOT NULL,
    QNT_PRODUTO DECIMAL NOT NULL,
    LOCAL_PRODUTO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
    QUANTIDADE DECIMAL(5,3) NOT NULL,
    PRODUTO INT NOT NULL,
    PEDIDO INT NOT NULL,
	CONSTRAINT FK_PRODUTOS FOREIGN KEY (PRODUTO)
    REFERENCES PRODUTOS(COD_PRODUTO),
    CONSTRAINT FK_PEDIDOS_PRODUTOS FOREIGN KEY (PEDIDO)
    REFERENCES PEDIDOS(COD_PEDIDO),
    PRIMARY KEY (PRODUTO, PEDIDO)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
	PRODUTO_FORNECIDO INT NOT NULL,
    FORNECEDOR INT NOT NULL,
	CONSTRAINT FK_PRODUTOS_FORNECEDORES FOREIGN KEY (PRODUTO_FORNECIDO)
    REFERENCES PRODUTOS(COD_PRODUTO),
    CONSTRAINT FK_FORNECEDORES_PRODUTOS FOREIGN KEY (FORNECEDOR)
    REFERENCES FORNECEDORES(COD_FORNECEDOR),
    PRIMARY KEY (PRODUTO_FORNECIDO, FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_FILIAIS(
    QUANT_PROD_FIL DECIMAL(5,3),
    PRODUTO_FILIAL INT NOT NULL,
    FILIAL INT NOT NULL,
	CONSTRAINT FK_PRODUTOS_FILIAIS FOREIGN KEY (PRODUTO_FILIAL)
    REFERENCES PRODUTOS(COD_PRODUTO),
    CONSTRAINT FK_FILIAIS_PRODUTOS FOREIGN KEY (FILIAL)
    REFERENCES FILIAIS(COD_FILIAL),
    PRIMARY KEY (PRODUTO_FILIAL, FILIAL)
    
);